oravirt/ansible-oracle

drracattack-full-install.yml
group_vars/drracattack

This to the next release of racattack to be able to add some DR nodes

add drrackattack

---

roles/oradb-create/tasks/main.yml

Now greps on exact match of db name

fixes #35 - added -w to grep

---

roles/orahost/tasks/main.yml

Fix issue #59

---

roles/oraswgi-install/tasks/curl.yml

one quote too much

---

roles/oradb-manage-grants/tasks/main.yml
roles/oradb-manage-parameters/tasks/main.yml
roles/oradb-manage-pdb/tasks/main.yml
roles/oradb-manage-redo/tasks/main.yml
roles/oradb-manage-tablespace/tasks/main.yml
roles/oradb-manage-users/tasks/main.yml

Some variable structures are really huge. They create a lot of spam during the execution of the roles.

reduced output during execution of tole with label in loop_control

---

roles/oradb-create/templates/dbca-create-db.rsp.12.2.0.1.j2
roles/oradb-manage-db/templates/dbca-create-db.rsp.12.2.0.1.j2
roles/oradb-manage-db/templates/dbca-create-db.rsp.18.3.0.0.j2

fix for #153 : Syntax error in nationalCharacterSet

---

roles/oradb-manage-db/templates/dbca-create-db.rsp.19.3.0.0.j2
roles/oraswdb-install/defaults/main.yml
roles/oraswdb-install/tasks/19.3.0.0.yml
roles/oraswdb-install/templates/db-install.rsp.19.3.0.0.j2

Clusterware / Resart is not included

Support for Oracle 19c Databases

---

group_vars/vbox-si-fs/vbox-si-fs.yml
roles/orahost/tasks/main.yml

- file system creation (fsopts)
- mount/fstab option (mntopts)

Add optional parameters to host_fs_layout for

---

roles/oradb-manage-db/templates/dbca-create-db.rsp.21.3.0.0.j2
roles/oraswdb-install/defaults/main.yml
roles/oraswdb-install/tasks/21.3.0.0.yml
roles/oraswdb-install/templates/db-install.rsp.21.3.0.0.j2

This is only the support for Database. Oracle Restart is coming later.

added Support for Oracle 21c Database

---

.github/workflows/changefile-exists.yml
changelogs/fragments/276-github-actions.yml

The Action will check for changelog files in Pull-Requests.

github Actions: check antsibull changelog files

---

changelogs/fragments/301-include.yml
roles/orahost/tasks/main.yml
roles/orahost_ssh/tasks/main.yml
roles/orahost_storage/tasks/main.yml
roles/oraswdb_manage_patches/tasks/db-home-patch.yml
roles/oraswgi_manage_patches/tasks/main.yml

Replace include with include_tasks due to deprecation warning

---

changelogs/fragments/128-oradb_manage_grants.yml
roles/oradb_manage_grants/tasks/main.yml

Refactoring introduced a bug that makes the role run into problems, this PR fixes it.

fix refactoring bug

---

.github/workflows/stale.yml
changelogs/fragments/github_action_stale.yml

github action: typo fix in stale issues & PRs

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/assert_python.yml
changelogs/fragments/dploy_collection.yml
changelogs/fragments/github_action_stale.yml
changelogs/fragments/role_orasw_download_patches.yml
changelogs/fragments/sw_meta_assert.yml
galaxy.yml

v3.6.0
======
Minor Changes
-------------
- added new orasw_download_patches role (oravirt#332)
- common: assert python2 interpreter on OL/RHEL7 (oravirt#330)
- github action: deploy collection (oravirt#324)
- github action: stale issues & PRs  (oravirt#326)
- orasw_meta: added central assert tasks for ansible-oracle (oravirt#325)

Release 3.6.0

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/ansible-lint-6141.yml
changelogs/fragments/rman_catalog_register.yml
changelogs/fragments/sles_os_packages.yml
galaxy.yml

Minor Changes
-------------
- added task to REGISTER DATABASE in Rman Catalog (oravirt#336)
- ansible-lint: Update to 6.14.4 (oravirt#329)
- orahost: improve oracle os packages selection for Suse (oravirt#337)

Release 3.7.0

---

changelogs/fragments/oracle_sqldba.yml
plugins/modules/oracle_sqldba.py

oracle_sqldba: Bugfix for Python3

---

.pre-commit-config.yaml
changelogs/fragments/pre-commit.yml

This improves the PR oravirt#344

pre-commit: Bugfix for known issue from ansible-oracle 3.8.0

---

changelogs/fragments/db_facts.yml
roles/oradb_facts/tasks/db_facts.yml
roles/oradb_facts/tasks/main.yml

oradb_facts: Bugfix for missing default variable definitions

---

changelogs/fragments/listener_home_config.yml
roles/oradb_manage_db/vars/main.yml

oradb_manage_db: Bugfix for undefined variable listener_home_config

---

changelogs/fragments/builder.yml
execution-environment.yml
tools/ansible/requirements_ansible.txt
tools/dev/requirements_dev.txt

This PR does some updates for building execution-evnrironments and the development environment for `ansible-oracle`.

Tools for Ansible

---

changelogs/fragments/remove_screen_from_default.yml
roles/common/README.md
roles/common/defaults/main.yml

Implementation for enhancement oravirt#495.

Remove screen from default common packages list on rhel8,9

---

changelogs/fragments/cvuqdisk-on-fips.yml
roles/oraswgi_install/tasks/12.1.0.1.yml
roles/oraswgi_install/tasks/12.1.0.2.yml
roles/oraswgi_install/tasks/12.2.0.1.yml
roles/oraswgi_install/tasks/18.3.0.0.yml
roles/oraswgi_install/tasks/19.3.0.0.yml
roles/oraswgi_install/tasks/install_cvuqdisk.yml
roles/oraswgi_install/tasks/runcluvfy.yml

Fix for issue https://github.com/oravirt/ansible-oracle/issues/430

Enable cvuqdisk install on FIPS systems

---

plugins/modules/oracle_asmdg.py
plugins/modules/oracle_asmvol.py
plugins/modules/oracle_datapatch.py
plugins/modules/oracle_facts.py
plugins/modules/oracle_gi_facts.py
plugins/modules/oracle_grants.py
plugins/modules/oracle_job.py
plugins/modules/oracle_jobclass.py
plugins/modules/oracle_jobschedule.py
plugins/modules/oracle_jobwindow.py
plugins/modules/oracle_ldapuser.py
plugins/modules/oracle_opatch.py
plugins/modules/oracle_parameter.py
plugins/modules/oracle_pdb.py
plugins/modules/oracle_privs.py
plugins/modules/oracle_profile.py
plugins/modules/oracle_redo.py
plugins/modules/oracle_role.py
plugins/modules/oracle_rsrc_consgroup.py
plugins/modules/oracle_services.py
plugins/modules/oracle_sql.py
plugins/modules/oracle_stats_prefs.py
plugins/modules/oracle_tablespace.py
plugins/modules/oracle_user.py

Changed Shebang line to recommend method and fixes #521

fix: :bug: Change shebang line to recommend method
