oravirt/ansible-oracle

- orahost/defaults/main.yml
- orahost/tasks/main.yml
Suggesting this patch so that udev persistence does not require asmlib packages. 
This is for role: orahost
Split the ASMlib RPM packages out of the main package list and put them in their own.
If user selects device_persistence == 'asmlib' then this RPM group is installed.
> Separate asmlib package requirements 

- oraasm-createdg/templates/asmca-createdg.sh.j2
Failure groups could be named when diskgroups are in high or
normal redundancy. Oracle doesn't support Failure Groups in
external redundancy. Please do not use them!
Example:
```
- diskgroup: test
properties:
- {redundancy: normal, ausize: 4}
attributes:
- {name: compatible.rdbms, value: 11.2.0.4.0}
- {name: compatible.asm, value: 12.1.0.2.0}
disk:
- {device: /dev/sdf, asmlabel: test01, failgroup: fg1}
- {device: /dev/sdg, asmlabel: test02, failgroup: fg2}
```
> added support for failgroup parameter in create diskgroup

- orahost/defaults/main.yml
- orahost/tasks/main.yml
```
$ pwd
ansible-oracle
$ grep -R oracle_sysconfig *
orahost/defaults/main.yml:  oracle_sysconfig:
orahost/tasks/main.yml:    with_items: oracle_sysconfig
```
IMHO, that names of the variable *_sysconfig, which indeed is used by the module sysctl,
and the values finally go to /etc/sysctl.conf, not something in /etc/sysconfig/ dir.
So, my opinion+question is, this variable needs to be called like: oracle_sysctl :+1:
> Change the variable oracle_sysconfig by oracle_sysctl.

- oraswdb-install/tasks/main.yml
- oraswgi-install/tasks/main.yml
Installing from unpacked local files without using a nfs server
was not possible, due to wrong when clause in tasks for mount/umount
of nfs.
The detection of install_from_nfs has been fixed and works like expected.
> bugfix Mount nfs share with installation media

- orahost-logrotate/defaults/main.yml
The new role orahost-logrotate has been enhanced and modified.
oracle_base is used to get the right directories for logfiles.
Removed copytruncate, this is not required anymore from 11.2 onwards.
Added missing alert.log for ASM.
> enhancements in orahost-logrotate

- cxoracle/defaults/main.yml
- oradb-create/defaults/main.yml
- oradb-delete/defaults/main.yml
- oraswdb-install/defaults/main.yml
This change is the 1st preparation which is needed for the possibility
to define a custom ORACLE_HOME for each database.
The following examples shows the usage of a custom ORACLE_HOME for the
racdb database. The value from home is ignored but the variable is requirred!
oracle_version_db is requirred for choosing the correct installation
media.
Example:
- home: dbhome_1
oracle_db_name: racdb
oracle_home: /u01/app/oracle/product/12.1.0.2/dbhome_1
oracle_version_db: 12.1.0.2
> preparation for using different ORACLE_HOME for each Database

- roles/oradb-create/templates/dbca-create-db.rsp.11.2.0.3.j2
- roles/oradb-create/templates/dbca-create-db.rsp.11.2.0.4.j2
- roles/oradb-create/templates/dbca-create-db.rsp.12.1.0.1.j2
- roles/oradb-create/templates/dbca-create-db.rsp.12.1.0.2.j2
The characterset and the ncharacterset can be defined for each database.
The old defaults are still used, until the parameter has been defined in
oracle_databases.
Example:
```
- home: db_home1
oracle_db_name: ORCL
characterset: WE8MSWIN1252
ncharacterset: AL16UTF16
```
> Added Support for Characterset for each Database

- roles/common/defaults/main.yml
- roles/common/tasks/main.yml
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
ansible-oracle gets compatibility against Suse Linux Enterprise Server.
Currently only 12.1 is supported.
The Firewall could not be disabled at the moment. You have to disable it
before using ansible-oracle. Normaly the installation of SLES12.1 disables
the sshd from outside and a change in the firewall is requirred. Please
disable it at this point.
Known Issues:
- missing oracleasm-support on SLES
SuSe includes the kernel modules for ASMlib but the oracleasm-support is
missing on the installation media. Please install it before using ansible-oracle
with enabled ASM support.
The RPM can be downloaded from Oracle:
http://www.oracle.com/technetwork/server-storage/linux/asmlib/sles12-2714894.html
> hostroles for compatibility against SLES12.1

- roles/common/defaults/main.yml
Use the latest epel-release package to download from fedoraproject.org instead of fixed version as these URL's get obsolete.
> use latest epel-release instead of fixed version

- roles/oradb-create/templates/dbca-create-db.rsp.12.2.0.1.j2
The DBCA creates the following error when templateName with '"'
are used:
[FATAL] [DBT-10325] Template file option is not specified.
> bugfix for templateName in dbca-create-db.rsp.12.2.0.1.j2

- roles/oradb-create/tasks/main.yml
Custom dbca-templates can be used within dbca_templatename inside
oracle_databases. The file is copied as a jinja2 template when the
value is not 'New_Database.dbt' ,'General_Purpose.dbc' or
'New_Database.dbt'.
> copy custom dbca_templatename to ORACLE_HOME

- roles/orahost/defaults/main.yml
The RPM psmisc has been added for opatch.
'fuser' is needed for opatch from Version 12.1
Details: Support-Note 1581604.1
> added psmisc for 12.1+ opatch apply

- roles/orahost/tasks/main.yml
As soon as you upgrade to Oracle Linux 6.10, the version check will fail.
> Bugfix: the supported OS check should use version semantics

- roles/oraswdb-install/defaults/main.yml
It should work against unsupport OS as well.
> oraswdb-install: make init/systemd much more robust

- roles/orahost/defaults/main.yml
All other roles use device_persistence: asmlib as default except
orahost. This has been fixed.
> orahost: Make device_persistence consistent against other roles

- roles/oraswdb-install/defaults/main.yml
- roles/oraswdb-install/tasks/install-home-db.yml
The licensed options in the Oracle binaries are configurable.
All options are disabled by default!
The following variable could be used to change the default:
```
oracle_EE_options_112:
- {option: dm           , state: false }
- {option: dv           , state: false }
- {option: lbac         , state: false }
- {option: olap         , state: false }
- {option: partitioning , state: false }
- {option: rat          , state: false }
oracle_EE_options_121:
- {option: dm           , state: false }
- {option: olap         , state: false }
- {option: partitioning , state: false }
- {option: rat          , state: false }
oracle_EE_options_122:
- {option: oaa          , state: false }
- {option: olap         , state: false }
- {option: partitioning , state: false }
- {option: rat          , state: …
```
> oraswdb-install: Options in oracle executable are configurable

- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
A problem with creating the inventory occurs when host_fs_layout has
a definition with /u01 and /u01/app/oracle/diag. The result is a missing
permission to create /u01/app/oraInventory.
This has been fixed.
> sufficient permissions to access the inventory '/u01/app/oraInventory'

- roles/oradb-manage-db/defaults/main.yml
- roles/oradb-manage-db/tasks/listener.yml
- roles/oradb-manage-db/tasks/main.yml
- roles/oradb-manage-db/tasks/manage-db.yml
- roles/oradb-manage-grants/defaults/main.yml
- roles/oradb-manage-grants/tasks/main.yml
- roles/oradb-manage-parameters/defaults/main.yml
- roles/oradb-manage-parameters/tasks/main.yml
- roles/oradb-manage-pdb/defaults/main.yml
- roles/oradb-manage-pdb/tasks/main.yml
- roles/oradb-manage-redo/defaults/main.yml
- roles/oradb-manage-redo/tasks/main.yml
- roles/oradb-manage-roles/defaults/main.yml
- roles/oradb-manage-roles/tasks/main.yml
- roles/oradb-manage-services/defaults/main.yml
- roles/oradb-manage-services/tasks/main.yml
- roles/oradb-manage-tablespace/defaults/main.yml
- roles/oradb-manage-tablespace/tasks/main.yml
- roles/oradb-manage-users/defaults/main.yml
- roles/oradb-manage-users/tasks/main.yml
db_unique_name is changing the default name for service during connectiong to the instance. A non default port for the listener is also usable whith listener_port in oracle_databases.
The listener_port is needed inside the pdb-configuration as well:
```
oracle_pdbs:
- pdb_name: orclpdb1
listener_port: 1522
...
```
> oradb-manage-*: support for service_name + listener_port

- roles/oradb-manage-db/LISTENER.md
- roles/oradb-manage-db/defaults/main.yml
- roles/oradb-manage-db/tasks/listener.yml
- roles/oradb-manage-db/tasks/listener_details.yml
- roles/oradb-manage-db/tasks/main.yml
- roles/oradb-manage-db/tasks/sqlnet.yml
- roles/oradb-manage-db/tasks/tnsnames.yml
- roles/oradb-manage-db/templates/listener_details.j2
- roles/oradb-manage-db/templates/tnsnames.ora.j2
- roles/oradb-manage-db/templates/tnsnamesdgfailover2.ora.j2
This PR includes all changes for creating tnsnames.ora and listener.ora with new inventory structure.
It is very flexible and a mandatory requiement for the future Data-Guard role.
> oradb-manage-db: Support for listener.ora, sqlnet.ora and tnsnames.ora with new inventory structure

- roles/oradb-manage-db/tasks/manage-db.yml
The support for a dedicated instance_name during database creation
was missing for the role oradb-manage-db.
> oradb-manage-db: Support for oracle_db_instance_name in oracle_databases

- roles/oradb-manage-db/defaults/main.yml
- roles/oradb-manage-db/tasks/main.yml
- roles/oradb-manage-db/tasks/manage-db.yml
- roles/oradb-manage-db/templates/dbca-create-db.rsp.11.2.0.3.j2
- roles/oradb-manage-db/templates/dbca-create-db.rsp.11.2.0.4.j2
- roles/oradb-manage-db/templates/dbca-create-db.rsp.12.1.0.1.j2
- roles/oradb-manage-db/templates/dbca-create-db.rsp.12.1.0.2.j2
- roles/oradb-manage-db/templates/dbca-create-db.rsp.12.2.0.1.j2
- roles/oradb-manage-db/templates/dotprofile-db.j2
The usage of dbca_templatename in oracle_database has been changed.
The template is copied to $ORACLE_HOME/assistant/dbca/templates for
each database as <db_name>_customexample.dbt. This allow the usage
of jinja2 in the template for each database.
Be aware:
The jinja2 variable 'item' has been changed to 'dbh' in the template
files.
dbca_templatename: customexample.dbt
> oradb-manage-db: new handling of custom dbca-templates

- roles/oradb-manage-users/tasks/main.yml
The password of existing users could be changed with:
users:
- schema: dbsnmp
update_password: always
state: unlocked
This is needed for existing accounts. By default only new
created accounts will get the password, because the role
will always set the password for the user when update_password
is set to 'always'!
> oradb-manage-users: added support for update_password

- roles/oraswdb-install/defaults/main.yml
- roles/oraswdb-install/tasks/install-home-db.yml
- roles/oraswdb-install/tasks/main.yml
This feauture was removed during the change to the new inventory
structure.
The task only changes an option, if a file for
$ORACLE_HOME/install/<enable|disable>_.log is not existing!
The licensed options in the Oracle binaries are configurable.
All options are disabled by default!
To activate an option set state to 'True'.
More details could be found in Doc ID 948061.1
The following variable could be used to change the default:
oracle_EE_options_112:
- {option: dm           , state: false }
- {option: dv           , state: false }
- {option: lbac         , state: false }
- {option: olap         , state: false }
- {option: partitioning , state: false }
- {option: rat          , state: false }
oracle_EE_options_121:
- {option: dm           , state: false }
- {option: olap         , state: …
> oraswdb-install: Configure license option in Oracle Executables

- roles/oradb-manage-db/defaults/main.yml
The init_parameters defines the parameers for init.ora during DBCA and
oradb-manage-parameters. Sometimes a parameter should not be sent to DBCA.
The parameter dbca could be used. The default is True when the parameter is missing.
init_parameters:
- {name: pga_aggregate_target, value: '200M', scope: both, state: present, dbca: False}
> oradb-manage-db: Custom configuration of init_parameters for DBCA

- roles/orahost/tasks/main.yml
The commit leads to an installation of ASMlib tools when no
ASM-Diskgroups were defined:
orahost: Make device_persistence consistent against other roles
This has beend fixed. The RPMs are only installed when the
variable asm_diskgroups is defined.
> orahost: only install ASMLib Packages with defined Diskgroups

- roles/orahost-storage/defaults/main.yml
- roles/orahost-storage/tasks/main.yml
- roles/orahost-storage/templates/oranfstab.j2
The following variable is needed to configure dNFS for Oracle.
The fstab and /etc/oranfstab are automaically configured.
Multiple exports and networks are possible.
There is no removal option at the moment.
Configuration:
oradnfs:
- server: nfsserver
ips:
- local: dbserver
path: nfsserver
exports:
- export: /nfs/oradata
mount: /u02/oradata
> Support for dNFS

- roles/orahost/tasks/main.yml
'repository not found' if passing empty string to yum 'enablerepo' parameter #46517
This problem has been introduced in Ansible 2.7.0. This
fix hopefully prevent future problems.
> orahost: Bugfix for Ansible Issue #46517

- roles/oradb-manage-db/templates/listener_details.j2
Addional parameters could be configured for non GI/Restart
installations:
```
oracle_listeners_config:
LISTENER1522:
home: 12102-latest
parameter:
- param: "INBOUND_CONNECT_TIMEOUT"
value: 0
- param: "USE_SID_AS_SERVICE"
value: "ON"
```
listener.ora:
```
INBOUND_CONNECT_TIMEOUT_LISTENER1522=0
USE_SID_AS_SERVICE_LISTENER1522=ON
```
> oradb-manage-db: custom parameter for listener.ora

- roles/oraswdb-install/files/manage_oracle_rdbms_procs.sh
- roles/oraswdb-install/tasks/init.yml
- roles/oraswdb-install/tasks/main.yml
- roles/oraswdb-install/templates/dbora.j2
- roles/oraswdb-install/templates/oracle-rdbms-service.j2
The stupid dbstart and dbstop has been replaced by a completly new designed script manage_oracle_rdbms_procs.sh.
The script is placed in /usr/local/bin and must be executed as the owner of the Oracle software. Instances are started when the state in oratab is 'Y' or 'M' for only 'startup mount' which is important in data-guards to protect against accidently using the active data-guard option.
All listeners are started when 'listener_name' is defined in oracle_databases for the instance.
> oraswdb-install: added autostart support to multiple listeners for database in filesystems

- roles/oradb-manage-users/tasks/main.yml
The parameter profile was missind in users.
Example:
- home: 12201-latest
oracle_db_name: testdb
users:
- schema: c##check_mk
profile: c##check_mk_profile
> oradb-manage-users: Added support for profiles

- roles/oraswdb-install/files/manage_oracle_rdbms_procs.sh
Oracle changed the presentation of process names with 12.1.
The used 'ps -C' was not able to find the pmon on the
process list.
This is the fix for #140.
> oraswdb-install: Fixed autostart for 11.2 databases

- roles/oraswdb-install/files/manage_oracle_rdbms_procs.sh
Fixes #165.
Enables use of -s|--ORACLE_SID option.
```
/usr/local/bin/manage_oracle_rdbms_procs.sh -a start -s orcl18
/usr/local/bin/manage_oracle_rdbms_procs.sh -a stop --ORACLE_SID orcl18
```
Note that if `ORACLE_SID` has been set in the shell prior to running the script (e.g. from previously sourcing the ~/.profile_<ORACLE_SID>"), and the script is run without the SID option then the database with this associated SID *will be the only one actioned* because the ORACLE_SID variable is used directly in the script. Not sure if this should be the default behaviour. Running via systemd unit file (e.g. systemctl start oracle-rdbms.service) is unaffected (will run against all in /etc/oratab).
> developed ORACLE_SID option in manage_oracle_rdbms_procs.sh

- roles/oradb-datapatch/defaults/main.yml
- roles/oradb-datapatch/tasks/main.yml
The role has been rewritten for Single-Instance configurations.
This role can be used to install PSU/RU for 12.1.0.2+ databases.
The following roles can be used to install a new PSU:
- oraswdb-manage-patches
- oradb-datapatch
The role starts listener and instances in SI configurations, because
oraswdb-manage-patches is stopping the listener and instances for the
ORACLE_HOME.
Don't forget the updates in ansible-oracle-modules for this commit.
- oravirt/ansible-oracle-modules#92
- oravirt/ansible-oracle-modules#98
> oradb-datapatch: extended support for datapatch

- roles/oraswgi-manage-patches/tasks/main.yml
The parameter rolling has beend added to support non rolling
installations for opatchauto.
The default for rolling is True
gi_patches:
18.3.0.0:
opatchauto:
- patchid: 29301682
rolling: False
This PR needs 2 other PRs 
- oravirt/ansible-oracle-modules#100
- #159
> oraswgi-manage-patches: added Support for non rolling apply in GI

- roles/orahost/tasks/main.yml
There is no guarantee that nslookup is installed
on modern systems. Use host instead, because that
is availible on every system.
> orahost: replace nslookup with host

- roles/oradb-rman/defaults/main.yml
The variable rman_tns_admin is dependent on oracle_base
instead of /u01/app/oracle/rman/network/admin
> oradb-rman: rman_tns_admin depends on oracle_base

- roles/oraswdb-manage-patches/tasks/db-home-patch.yml
Conflicting one-off patches have to be removed before applying opatchauto.
- Situation:
- DB 12.1.0.2 EE
- PSU Jan 19
- One Off Patch 18633374 (among others)
- Objective:
- PSU Apr 19
- Problem:
- conflicting patch 18633374 has to be removed before installing PSU Apr 19
- Suggested solution:
- Copy (duplicate) task "db-opatch | Manage patches for DB"
- new name: "db-opatch | Remove unwanted patches from DB"
- insert just before "db-opatch | Manage opatchauto patches for DB (non-gi)"
- when clause extended by 'item.state == "absent"'
- (sideshow: removing 18633374 requires https://github.com/oravirt/ansible-oracle-modules/pull/110
==> Is there a different solution for the problem of conflicting patches?
> Remove unwanted or conflicting patches from DB

- roles/cxoracle/tasks/main.yml
The newer versions of cx_oracle could not be installed with pip2
without Python3. The change to Python3 needs more tests in ansible-oracle-modules.
This is a quick fix to install cx_Oracle with pip2 for ansible-oracle.
This is a PR for #209
> cx_oracle: Limit installed Version to <8.0

- roles/common/tasks/main.yml
Oracle changed the configuration of public-yum.repo in January 2019 for OL7.
Downloading the old file will mess up the repository configuration.
This is the PR for #204
> common: Skip downloading public-yum.repo on newer OL7 versions

- roles/orasw-meta/defaults/main.yml
The filename for OPatch was missing in oracle_opatch_patch.
> orasw-meta: added OPatch for 19c

- roles/common/defaults/main.yml
- roles/common/tasks/main.yml
- roles/orahost/tasks/RedHat-8.yml
- roles/orahost/tasks/main.yml
This PR adds support for OL8 and RHEL8 as OS.
Important Note:
Oracle 19.3 is not detecting OL8/RHEL8 as a valid OS. Please use a previous created GoldenImage as image for dsw-install.
> Support for OL8 and RHEL8

- roles/orahost/tasks/main.yml
Some Kernels do not allow an increase of hugepages without
enough free memory. When hugepages could not be allocated
during initial setup the execution of DBCA could fail due
to missing enough hugpages.
When vm.nr_hugepages is changed the filecache is flushed
and anoher execution of systcl -p is done - hopefully to
allocate the needed pages.
> orahost: new approach for setting hugepages during setup

- roles/orahost/tasks/main.yml
The following variables have been added:
- os_timezone: <not defined by default>
- os_hwclock: <ignored by default>
Example:
os_timezone: Europe/Berlin
> orahost: Added support for timezone change

- roles/oraswdb-install/tasks/19.3.0.0.yml
- roles/oraswdb-install/tasks/main.yml
The name for the installation archive in 19c could be defined in oracle_db_homes.
Example:
db_homes_config:
db198:
home: db198
version: 19.3.0.0
imagename: db_home_19.8.zip
The imagename defines the used filename for the archive to unzip.
Please create the archive with oui before:
$ORACLE_HOME/runInstaller -createGoldImage -silent -destinationLocation "${ORACLE_BASE}/db_golden_image
> oraswdb-install: Install 19c from Golden Image

- roles/common/tasks/main.yml
- roles/orahost/tasks/main.yml
- roles/oraswdb-install/tasks/install-home-db.yml
It is time to move to a much newer version of Ansible, due to desupport of really old used versions of Ansible for developing this project.
The new minimum version is 2.8 and this PR is tested against 2.8 and 2.9.
> changed minimum Ansible version to 2.8

- roles/orahost/defaults/main.yml
- roles/oraswdb-install/defaults/main.yml
- roles/oraswdb-install/tasks/install-home-db.yml
Oracle changed the logfile for chopt in 19c. This leads to problems with the old
impletation, due to recompiles of oracle binary for each execution of the task.
The new solution is not dependent on the logfile anymore.
Warning!
This change will recompile the binaries during the 1st execution, because
the statefile was not created with the old solution.
this PR fixes #219
> chopt: new strategy for change chopt options

- roles/cxoracle/tasks/main.yml
A new parameter has been added to support custom source definition for cx_Oracle.
This is needed when ansible-oracle is used in environments without public internet connectivity.
How to user?
Download cx_Oracle without installation:
pip install --download /tmp 'cx_oracle<8.0'
Store the file in a directory availible from target host.
Set follwoing variable in inventory:
cx_oracle_source="file:///tmp/cx_Oracle-7.3.0-cp27-cp27mu-manylinux1_x86_64.whl"
> cxoracle: Support custom installation source

- roles/oraswgi-install/defaults/main.yml
- roles/oraswgi-install/tasks/19.3.0.0.yml
The following variable has been added to support GI/Restart
installations from Golden-Images.
oracle_install_image_gi: grid_home_19.11.zip
Restrictions:
This is only supported for 19c at the moment.
Creating a Golden-Images for Oracle Restart requires a running installation of Oracle Restart.
> oraswgi-install: Install from Golden-Image

- roles/orasw-meta/defaults/main.yml
- roles/oraswdb-golden-image/meta/main.yml
- roles/oraswdb-golden-image/tasks/main.yml
- roles/oraswgi-golden-image/meta/main.yml
- roles/oraswgi-golden-image/tasks/main.yml
The role uses gridSetup.sh -silent -createGoldImage -destinationLocation
to create Golden Images from running installations.
The following variable must be set:
golden_image_dest: /u01/golden
oraswdb-golden-image: Create Golden-Images for installed ORACLE_HOMEs
The role uses runInstaller -silent -createGoldImage -destinationLocation
to create Golden Images from installed ORACLE_HOMEs.
The following variable must be set:
golden_image_dest: /u01/golden/
The role creates a custom destination directory for each
db_homes_installed.
directory = {{ golden_image_dest }}/{{ db_homes_installed.home}}
<db_homes_installed.home>
The directroies are created by oracle.
> Create Golden-Images for Oracle Restart and Database-Homes

- roles/orahost/tasks/main.yml
We cannot use factor_os so early in orahost, due to missing facter.rpm.
> orahost: Bugfix for factor_os is undefined

- roles/orahost/tasks/main.yml
lvsize in host_fs_layout did not change the lvol with underlying
Filesystem.
This has been change by adding resizefs=yes to the lvol task.
> orahost: added resizefs=yes

- roles/oradb-manage-db/tasks/tnsnames.yml
Currently having conditional state in tnsnames_installed is ignored and all entries found there are created. It does not even respect state: absent for removing tnsnames.ora entries.
With this change this gets fixed and tnsnames entry will only then exist, when state is defined to present in tnsnames_installed.
> fixed a problem with thsnames ignoring state in tnsnames_installed

- changelogs/fragments/274-listener_details.yml
- roles/oradb_manage_db/templates/listener_details.j2
This fixes issue #152 .
Make sure to use Jinja 2.10 or newer for namespaces.
> oradb_manage_db: Bugfix listener.ora for multiple Instances on 1 host

- .ansible-lint
- .github/workflows/ansible-lint.yml
- changelogs/fragments/277-ansible-lint.yml
- docker/Dockerfile
- docker/docker-compose.yml
Update ansible-lint to 6.6.1.
Added ansible-lint to Dockerfile. ansible-lint could be used with ansible in Docker Container together.
> ansible-lint: Move to  v6.6.1

- changelogs/fragments/273-readonly-homes.yml
- roles/oradb_manage_db/defaults/main.yml
- roles/oradb_manage_db/tasks/listener_details.yml
- roles/oradb_manage_db/tasks/sqlnet.yml
- roles/oradb_manage_db/tasks/tnsnames.yml
- roles/oraswdb_install/defaults/main.yml
- roles/oraswdb_install/tasks/19.3.0.0.yml
- roles/oraswdb_install/tasks/21.3.0.0.yml
- roles/oraswdb_install/tasks/roohctl.yml
This PR introduce the ability to use read-only ORACLE_HOMEs for Database-Homes.
Add the following  to oracle_homes
```
db_homes_config:
db19-si-ee:
oracle_home_name: db19_si_ee
readonly_home: true
```
The default for `readonly_home` is `false`. If it is `true`, the parameter `oracle_home_name` must be set as well.
Important: Onlly alphanumeric, numbers and underscore characters are allowed for `oracle_home_name`.
The mode for an ORALCE_HOME is only set during the initial runInstaller execution.
**Do not change `readonly_home` after installation, because that creates some problems for existing Listeners and Database Instances.**
> Support for read-only ORACLE_HOMEs

- changelogs/fragments/284-ol8-fix.yml
- roles/oraswdb_install/tasks/19.3.0.0.yml
Installing Oracle 19.3 on a RedHat 8 box will raise:
`TASK [opitzconsulting.ansible_oracle.oraswdb_install : install_home_db | Install Oracle Database Server] ***
Sunday 09 October 2022  10:01:22 +0200 (0:00:00.164)       0:03:56.251 ********
fatal: [molecule-install_orahome-default]: FAILED! => {"changed": true, "cmd": ["/opt/oracle/product/19c/runInstaller", "-responseFile", "/opt/oracle/stage/rsp/19c_molecule-installorahome-default.rsp", "-ignorePrereq", "-silent", "-waitforcompletion"], "delta": "0:00:02.106271", "end": "2022-10-09 10:01:25.339855", "failed_when_result": true, "msg": "non-zero return code", "rc": 255, "start": "2022-10-09 10:01:23.233584", "stderr": "", "stderr_lines": [], "stdout": "Launching Oracle Database Setup Wizard...\n\n[WARNING] [INS-08101] Unexpected error …
> Make it possible to install Oracle 19.3 on RedHat 8

- changelogs/fragments/285-ocenv-deploy-fix.yml
- roles/oradb_manage_db/defaults/main.yml
- roles/oradb_manage_db/tasks/manage-db.yml
While I can understand the utility of the ocenv script, it should be possible to decide if you want it deployed or not.
> Make the deployment of ocenv configurable

- changelogs/fragments/sqlplus-pipe-byte-streams-fix.yml
- plugins/modules/oracle_sqldba
When using oracle_sqldba module with a rhel8 box with python3 I get the following error:
```
TASK [Shutdown the database.] **************************************************
Tuesday 18 October 2022  13:47:52 +0300 (0:00:01.854)       0:00:01.882 *******
fatal: [instance]: FAILED! => {"changed": false, "msg": "[ERR]\nCould not call sqlplus. memoryview: a bytes-like object is required, not 'str'. called: /opt/oracle/product/19c/bin/sqlplus -l -s /nolog."}
```
It can be reproduced with a task like the following:
```
tasks:
- name: Shutdown the database.
oracle_sqldba:
sql: "shutdown immediate"
scope: db
oracle_home: /opt/oracle/product/19c
oracle_db_name: MOLDB01
become_user: oracle
```
> Use byte streams for sqlplus process communication

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/284-ol8-fix.yml
- changelogs/fragments/285-ocenv-deploy-fix.yml
- changelogs/fragments/sqlplus-pipe-byte-streams-fix.yml
- galaxy.yml
v3.2.0
======
Bugfixes
--------
- oracle_sqldba module: Use byte streams for sqlplus process communication.
- oradb-manage-db: Make the deployment of ocenv configurable (#285)
- oraswdb_install: Make it possible to install Oracle 19.3 on RedHat 8 (#284)
> Release: ansible-oracle v3.2.0

- changelogs/fragments/dbca_templatepath.yml
- roles/oradb_manage_db/tasks/manage-db.yml
Currently `dbca_templatename` can't refer to a file outside of the `./templates` sub-directory. This is a problem if you maintain a location with various dbca template files, outside of the role/playbook structure. So, it should be possible to provide the source path of the dbca template as well. I know that you can set `dbca_copy_template` to `false` and copy the template file yourself, but I feel that `oradb_manage_db` role should be smart enough to handle this simple scenario by its own. Another way to address this would be to specify the full path as part of the `dbca_templatename` property and apply a `basename` filter here and there, but I think it is more complicated and it doesn't pay off the trouble.
> Add option to set the path of the dbca template

- changelogs/fragments/manage_oracle_rdbms_procs.yml
- roles/oraswdb_install/files/manage_oracle_rdbms_procs.sh
The script invoked by systemd to start/stop databases is not working properly.
```
root@molecule--default ~ # systemctl start oracle-rdbms
Job for oracle-rdbms.service failed because the control process exited with error code.
See "systemctl status oracle-rdbms.service" and "journalctl -xe" for details.
root@molecule--default ~ # journalctl -xe
...
Nov 13 09:50:28 molecule--default systemd[1]: Starting Oracle Database(s) and Listener...
-- Subject: Unit oracle-rdbms.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit oracle-rdbms.service has begun starting up.
Nov 13 09:50:28 molecule--default manage_oracle_rdbms_procs.sh[336423]: for MOLDB:/opt/oracle/product/19c:Y
Nov 13 09:50:28 molecule--default …
```
> Fix oracle export environment variables

- changelogs/fragments/custom_template_path.yml
- roles/common/defaults/main.yml
- roles/common/tasks/main.yml
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
- roles/oraswdb_install/defaults/main.yml
- roles/oraswdb_install/tasks/install-home-db.yml
For some custom/advanced setups it would be nice if we could customize some of the default provided templates. It is the case of `motd.j2` template from the common role, `sudoers.j2` from the orahost role (if for example I don't want NOPASSWD for sudo or I'd like access to a few commands only) and `dotprofile-home.j2` from oraswdb-install role. With the proposed changes I can create for example my own `dotprofile-home.j2`, place it in my templates/ folder in the root of my playbook directory and set `oracle_profile_template` to `"{{ playbook_dir }}/templates/dotprofile-home.j2"`. I can do all these manually through some post_tasks, of course, but it would unnecessarily complicate the playbook. Not to mention that generating dotprofile file can't be currently disabled. This patch adds also …
> Make some of the j2 templates source configurable

- changelogs/fragments/1-asmfd.yml
- changelogs/fragments/297-asmfd.yml
- roles/orahost_storage/tasks/main.yml
- roles/oraswgi_install/defaults/main.yml
- roles/oraswgi_install/tasks/19.3.0.0.yml
- roles/oraswgi_install/tasks/21.3.0.0.yml
- roles/oraswgi_install/tasks/asmcmd_dsset.yml
- roles/oraswgi_install/tasks/asmfd.yml
- roles/oraswgi_install/tasks/asmfd_disks.yml
- roles/oraswgi_install/tasks/main.yml
- roles/oraswgi_install/templates/grid-install.rsp.19.3.0.0.j2
- roles/oraswgi_install/templates/grid-install.rsp.21.3.0.0.j2
This is the expeimental implementation of ASMFD (ASM Filter Driver) in ansible-oracle.
It is experimentalk, due to an open question in the installation.
- Why is the `afd_discoerystring` needed in `oracle.install.asm.diskGroup.diskDiscoveryString`?
The Responsefile for the installation requires the `ASMFD discoverysting` in `asm_diskstring`, which is wrong but installation will fail with the correct value.
Workarround:
Change the `asm_diskstring` after initial setup of ASM.
I am not sure, if this is the right way.
=> This is why it is experimentell for the moment.
This PR fixes #129
> oraswgi_install: experimental support for ASMFD (Filter Driver)

- changelogs/fragments/customscripts_support.yml
- roles/oradb_manage_db/tasks/manage-db.yml
It should be possible to deploy all custom scripts defined in a dbca template. With this PR you may define the following section in your dbca template:
```
<CustomScripts Execute="true"><CustomScript script="{ORACLE_HOME}/assistants/dbca/templates/{{ dbh.oracle_db_name }}_post_install_script.sql"/></CustomScripts>
```
Then, `customscripts` variable for the database to be created should point out to the relevant custom scripts defined in the template:
```
- home: 19c
oracle_db_name: DUMMYDB
dbca_templatepath: templates/
dbca_templatename: dummydb.dbt
...
customscripts:
- post_install_script.sql
state: present
```
All defined custom scripts are copied over to the target remote `ORACLE_HOME/assistants/dbca/templates/`, from the same `dbca_templatepath` location. Like the …
> oradb_manage_db: support for dbca custom scripts

- changelogs/fragments/datapatch_alias_fix.yml
- plugins/modules/oracle_datapatch
When running datapatch module, the following warning is raised:
```
TASK [opitzconsulting.ansible_oracle.oradb_datapatch : oradb_datapatch | Run datapatch] ***
...
[WARNING]: Both option password and its alias password are set.
```
> Remove password alias from datapatch module.

- changelogs/fragments/ocenv_custom_bashrc.yml
- roles/oradb_manage_db/defaults/main.yml
- roles/oradb_manage_db/tasks/ocenv.yml
The default `ocenv` initialization in `.bashrc` file can cause issues, that is why it should be customizable. For example, on a newly provisioned DB server with `ocenv` installed, the EM agent deployment fails (see EM 12c/13c: Agent Deployment Fails at Remote Validations step with error "Banner check failed" (Doc ID 1453099.1)). This pull request introduces two new variables to control whether `.bashrc` should be changed (`ocenv_bashrc_init` variable) and how (`ocenv_bashrc_init_section` variable).
> oradb_manage_db: customize ocenv init in bashrc

- changelogs/fragments/311-orahost_sles153_packages.yml
- roles/orahost/defaults/main.yml
libcap1 is not available nor needed for SLES15, so here it should be also commented out
> fix oracle packages for SLES 15.3

- changelogs/fragments/pam_limits_config.yml
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
This PR adds possibility to switch on/off the configuration of pam.d entry in pam.d/login and security.d/limits.d/99-oracle-limits.conf for oracle user. It was currently only possible to exclude this by using skip_tags, now it should be possible also via inventory.
> add configuration variables for pam_limits

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/pam_limits_config.yml
- galaxy.yml
v3.5.0
======
This is a small monthly release of ansible-oracle.
Minor Changes
-------------
- add configuration variables for pam_limits to orahost (oravirt#317)
Deprecated Features
-------------------
- Removal of deprecated directory /inventory from repository with next release.
> Release: ansible-oracle v3.5.0

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- galaxy.yml
- roles/oradb_manage_tablespace/defaults/main.yml
> oradb_manage_tablespace: added missing defaults for password

- changelogs/fragments/sw_meta_assert.yml
- roles/orasw_meta/tasks/assert_oracle_databases.yml
- roles/orasw_meta/tasks/main.yml
This is the 1st step for adding central assert tasks to tesk the used inventory.
> orasw_meta: added central assert tasks for ansible-oracle (oravirt#325)

- changelogs/fragments/role_orasw_download_patches.yml
- roles/orasw_download_patches/.ansibledoctor.yml
- roles/orasw_download_patches/README.md
- roles/orasw_download_patches/defaults/main.yml
- roles/orasw_download_patches/meta/main.yml
- roles/orasw_download_patches/tasks/main.yml
This is a new role, that can be used to download all patches referenced in `oracle_sw_patches` plus current OPatch for all `db_homes_installed` versions.
Required variables:
- `mos_login`: login for My Oracle Support
- `mos_password`: password for My Oracle support
> new role orasw_download_patches

- changelogs/fragments/sles_os_packages.yml
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
This PR improves package selection for those different Suse releases. When using `oracle_packages_sles` this mechanism is disabled and `oracle_packages_sles` takes precedence.
> Improve package handling for sles

- changelogs/fragments/communiy_collection.yml
- roles/common/tasks/main.yml
- roles/orahost/tasks/main.yml
Remove following warnings during playbook execution:
> community.general.system.timezone has been deprecated. 
> You are using an internal name to access the community.general.timezone modules. This has never been supported or documented, and will stop working in community.general 9.0.0. This feature will be removed from community.general in version 9.0.0.
This has been fixed for different modules.
> Remove deprecation warnings for community.general 7.x

- .flake8
- .github/workflows/python-lint.yml
- .pre-commit-config.yaml
- changelogs/fragments/flake8.yml
- changelogs/fragments/python-lint.yml
- pyproject.toml
Added black und flake8 for linting of Python code.
Only modules with '*.py' are check by the linters.
Configurations for pre-commit and Github Actions are part of this Pull-Request.
> black and flake8 for Python modules

- .pre-commit-config.yaml
- changelogs/fragments/pre-commit.yml
The pre-commit for antsibull-changelog-lint is only availible on main branch at the moment. This will be changed in the future to the next release of antsibull-changelog.
> pre-commit: added antsibull-changelog-lint

- changelogs/fragments/cx_oracle.yml
- changelogs/fragments/python2_deprecated.yml
- roles/cxoracle/tasks/main.yml
The Release 3.8.0 of ansible-oracle changes the module `oracle_db`.
It requires an installation of Python3 and cx_Oracle for Python3.
The role cx_oracle installs cx_Oracle for Python2 and Python3 when '`ansible_python_interpreter`' points to Python2.
Please execute the role cx_oracle for old systems to install cx_Oracle for Python3.
This PR is mandatory for #342
> cx_oracle: Added installation of cx_Oracle for Python3

- changelogs/fragments/assert.yml
- roles/common/tasks/main.yml
The assert is not needed anymore, due to cx_Oracle installation for Python3 and Python2 when needed.
> common: removed assert for python due to oravirt#346

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/assert.yml
- changelogs/fragments/communiy_collection.yml
- changelogs/fragments/cx_oracle.yml
- changelogs/fragments/download_patch.yml
- changelogs/fragments/flake8.yml
- changelogs/fragments/ocenv.yml
- changelogs/fragments/opatchauto.yml
- changelogs/fragments/oraswdb_install_curl.yml
- changelogs/fragments/pre-commit.yml
- changelogs/fragments/python-lint.yml
- changelogs/fragments/python2_deprecated.yml
- changelogs/fragments/restart_spfile_parameters.yml
- galaxy.yml
v3.8.0
======
This is ansible-oracle 3.8.0.
The target database server must have Python3 installaed which is automatically done with role `orahost`.
It is mandatory for the module `oracle_db` which is used in `oradb_manage_db`.
Minor Changes
-------------
- Add restart possibility after scope=spfile init parameters change (oravirt#342)
- Add state=restarted to oracle_db (oravirt#342)
- Remove deprecation warnings for community.general 7.x (oravirt#339)
- black: adding black to pre-commit (oravirt#343)
- flake8: adding flake8 to pre-commit (oravirt#343)
- github Actions: adding Action for black and flake8 (oravirt#343)
- ocenv: version 2023-06-06 of ocenv environment script (oravirt#347)
- oracle_db: Refactoring code for flake8 (oravirt#342)
Breaking Changes …
> Release 3.8.0

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/oraimage.yml
- galaxy.yml
v3.8.1
======
Bugfixes
--------
- oraswdb_install: bugfix for imagename in db_homes_config  (oravirt#352)
> Release 3.8.1

- changelogs/fragments/assume_os.yml
- roles/oraswdb_install/tasks/19.3.0.0.yml
`CV_ASSUME_DISTID=OL7` was only set when no Golden-Image was used.
This needs to be changed to all installations on OL/RHEL8, because the needed fix is included in `OCW 19.6` or newer.
The problem is, that lot of customers only installs `DBRU` and not `OCW`.
The result is that `runInstaller` will fail.
I am responsible for this addional filter in #284 - sorry for that.
> oraswdb_install: enable CV_ASSUME_DISTID=OL7 for Golden-Image on OL/RHEL8

- changelogs/fragments/db_domain.yml
- changelogs/fragments/oradb_facts.yml
- roles/oradb_facts/README.md
- roles/oradb_facts/defaults/main.yml
- roles/oradb_facts/meta/main.yml
- roles/oradb_facts/tasks/db_facts.yml
- roles/oradb_facts/tasks/main.yml
- roles/oradb_manage_grants/README.md
- roles/oradb_manage_grants/meta/main.yml
- roles/oradb_manage_grants/tasks/main.yml
- roles/oradb_manage_parameters/meta/main.yml
- roles/oradb_manage_parameters/tasks/main.yml
- roles/oradb_manage_profiles/README.md
- roles/oradb_manage_profiles/meta/main.yml
- roles/oradb_manage_profiles/tasks/main.yml
- roles/oradb_manage_roles/meta/main.yml
- roles/oradb_manage_roles/tasks/main.yml
- roles/oradb_manage_services/meta/main.yml
- roles/oradb_manage_statspack/defaults/main.yml
- roles/oradb_manage_statspack/meta/main.yml
- roles/oradb_manage_statspack/tasks/main.yml
- roles/oradb_manage_tablespace/meta/main.yml
- roles/oradb_manage_tablespace/tasks/main.yml
- roles/oradb_manage_users/README.md
- roles/oradb_manage_users/meta/main.yml
- roles/oradb_manage_users/tasks/main.yml
- roles/orasw_meta/defaults/main.yml
- roles/orasw_meta/tasks/assert_oracle_databases.yml
`ansible-oracle` did not support a non default value for `db_domain` in the past.
This has been changed with some limitations:
- `db_domain` could be set in nonCDB or CDB
- `db_domain` in PDB is not supported at the moment
- `oracle_listeners_config` and `listener_installed` are needed to configure SID_LIST_LISTENER for CDB
This is not mandatory when db_domain is empty.
The connection to nonCDB/CDB will fail, when SID_LIST_LISTENER is missing!
The whole commit will be replaced by a refactered one in 4.0.
> Added support for db_domain in init.ora

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/assume_os.yml
- changelogs/fragments/curl.yml
- changelogs/fragments/db_domain.yml
- changelogs/fragments/oradb_facts.yml
- galaxy.yml
v3.9.0
======
This release adds support for db_domain in init.ora for nonCDB and CDB. Read (oravirt#356) for requirements and notes.
Minor Changes
-------------
- Added support for db_domain in init.ora (oravirt#356)
- oradb_facts: Backported role from dev release (oravirt#356)
- oraswdb_install: fixed wrong creates in curl.yml (oravirt#354)
Bugfixes
--------
- oraswdb_install: enable CV_ASSUME_DISTID=OL7 for Golden-Image on OL/RHEL8 (oravirt#355)
> Release 3.9.0

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/listener_dgmgrl.yml
- changelogs/fragments/manage_oracle_rdbms_procs.yml
- changelogs/fragments/oracle_sqldba.yml
- changelogs/fragments/pre-commit.yml
- galaxy.yml
v3.10.0
=======
Minor Changes
-------------
- oracle_sqldba: refactoring code, make it usable for ansible-doc, Python3 usable only (oravirt#361)
- oradb_manage_db: create _DGMGRL SID in listener.ora for EE only (oravirt#359)
Bugfixes
--------
- Bugfix for missing Listener autostart and readonly Homes in systemd (oravirt#358)
- oracle_sqldba: Bugfix for Python3 (oravirt#361)
- oraswdb_install: shellchecker for manage_oracle_rdbms_procs.sh (oravirt#358)
- pre-commit: Bugfix for known issue from ansible-oracle 3.8.0 (oravirt#383)
> Release 3.10.0

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/db_facts.yml
- changelogs/fragments/grant.yml
- galaxy.yml
v3.10.1
=======
Bugfixes
--------
- oradb_facts: Bugfix for missing default variable definitions (oravirt#366)
- oradb_manage_grant: Bugfix for broken grant on pdb with db_domain (oravirt#365)
> Release 3.10.1

- changelogs/fragments/rman_cron.yml
- roles/oradb_rman/tasks/main.yml
Cronjobs could be removed when state=absent is set.
> oradb_rman: added option state for cronjobs, disabled is optional now

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/beginner_patching.yml
- changelogs/fragments/ifile.yml
- changelogs/fragments/rman_cron.yml
- galaxy.yml
v3.11.0
=======
Minor Changes
-------------
- new vagrantbox example beginner_patching (oravirt#370)
- oradb_rman: added option state for cronjobs, disabled is optional now (oravirt#369)
Bugfixes
--------
- oradb_manage_db: bugfix for wrong IFILE path in tnsnames.ora and sqlnet.ora when readonly ORACLE_HOME is used (oravirt#371)
> Release 3.11.0

- changelogs/fragments/273_oradb_rman_absent_fix.yml
- roles/oradb_rman/tasks/main.yml
Original PR (#369) did allow removal of crontab jobs by specifying `state: absent` on rman_jobs entries. It however still tries to copy the rman script (which when state=absent does not really make sense and may even result in error if custom rman script got already removed/renamed on controller) and requires to add all time-related field options.
With this PR the task has been split into 2 - one task that will create required jobs (with state=present), and another one that will remove only the tasks with state=absent without requirement to provide `hour`, `minute`, `weekday` etc. Only name and state=absent is needed for removal. In addition the role will not try to copy rman scripts for which the state has been set to absent. It will however not remove them either from systems. They will …
> fix to enable removal of old jobs

- changelogs/fragments/375_nolog_modules.yml
- changelogs/fragments/375_oradb_facts_attributes.yml
- plugins/modules/oracle_awr
- plugins/modules/oracle_facts
- plugins/modules/oracle_job
- plugins/modules/oracle_jobclass
- plugins/modules/oracle_jobschedule
- plugins/modules/oracle_jobwindow
- plugins/modules/oracle_ldapuser
- plugins/modules/oracle_rsrc_consgroup
- roles/oradb_facts/tasks/db_facts.yml
This PR covers 2 things:
* it extends attributes mapped to `oracledb_facts` fact allowing customization which attributes will be exported by using `ordb_facts_categories` list parameter variable
* sets no_log on password fields of following modules:
* oracle_awr
* oracle_facts
* oracle_job
* oracle_jobclass
* oracle_jobschedule
* oracle_jobwindow
* oracle_ldapuser
* oracle_rsrc_consgroup
> extend oradb_facts and make password fields nolog

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/ansible-lint.yml
- changelogs/fragments/assert.yml
- changelogs/fragments/dbfacts.yml
- changelogs/fragments/listener_home_config.yml
- changelogs/fragments/lsof.yml
- changelogs/fragments/molecule.yml
- galaxy.yml
v4.3.0
======
This is a BETA Release of ansible-oracle. Do not use it in production environments!
Minor Changes
-------------
- ansible-lint v6.22.1 (oravirt#392)
- molecule: add tnsname configuration to shared inventory (oravirt#388)
- oradb_facts: Skip oracledb_facts when db not reachable (oravirt#387)
Bugfixes
--------
- common: install lsof for all RHEL/OL distributions (oravirt#391)
- oradb_manage_db: Bugfix for undefined variable listener_home_config (oravirt#386)
- orahost: Fix warning conditional statements should not include jinja2 templating (oravirt#391)
> Release 4.3.0 - 4th Beta Release of ansible-oracle

- changelogs/fragments/dbca-response.yml
- roles/oradb_manage_db/templates/dbca-create-db.rsp.12.2.0.1.j2
- roles/oradb_manage_db/templates/dbca-create-db.rsp.18.3.0.0.j2
- roles/oradb_manage_db/templates/dbca-create-db.rsp.19.3.0.0.j2
- roles/oradb_manage_db/templates/dbca-create-db.rsp.21.3.0.0.j2
The plaintext passwords are removed from dbca template. This is limited to RDBMS 12.2 or newer for the moment.
IMPORTANT!
Please change the passwords for existing database created before this security fix..
> oradb_manage_db: Remove visible password for sys, system and dbsnmp from dbca responsefile for 12.2+

- changelogs/fragments/dbca-response.yml
- changelogs/fragments/galaxy.aml
- changelogs/fragments/galaxy.yml
- changelogs/fragments/sqlnet_ansible.yml
- changelogs/fragments/tnsnames_alias.yml
- changelogs/fragments/wallet.yml
- galaxy.yml
v4.4.0
======
This is a BETA Release of ansible-oracle. Do not use it in production environments!
Minor Changes
-------------
- ansible-doctor: Update to 4.0.1 (oravirt#397)
- oradb_manage_db: Added support for aliasnames for Oracle Wallet (oravirt#400)
- oradb_manage_db: allow multiline values for keys in sqlnet_ansible.ora (oravirt#400)
- oradb_manage_wallet: New role for managing Oracle Wallets (oravirt#400)
- pre-commit: Update multiple hooks (oravirt#397)
Security Fixes
--------------
- dependabo: Update ansible-core in dev-tools (oravirt#398)
- dependabo: bump ansible from 6.7.0 to 8.5.0 in /tools/ansible (oravirt#395)
- dependabo: bump tj-actions/changed-files from 31 to 41 in /.github/workflows (oravirt#396)
- oradb_manage_db: Remove visible …
> Release 4.4.0 - 5th Beta Release of ansible-oracle

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/oradb_manage_wallet.yml
- extensions/molecule/shared_config/inventory/group_vars/all/oracle_db.yml
- galaxy.yml
- roles/oradb_manage_wallet/README.md
- roles/oradb_manage_wallet/defaults/main.yml
- roles/oradb_manage_wallet/tasks/wallet_manage_dbcredential.yml
- roles/oradb_manage_wallet/vars/main.yml
v4.4.1
======
This is a BETA Release of ansible-oracle. Do not use it in production environments!
Bugfixes
--------
- oradb_manage_wallet: fixed wrong dbpassword assignment, added debug option for password (oravirt#404)
> Release 4.4.1 - 5th Beta Release of ansible-oracle

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/opatch_apply.yml
- changelogs/fragments/wallet.yml
- changelogs/fragments/wallet2.yml
- galaxy.yml
v4.4.2
======
This is a BETA Release of ansible-oracle. Do not use it in production environments!
Bugfixes
--------
- oradb_manage_wallet: bugfix for broken Remove DB-Credentials (oravirt#406)
- oradb_manage_wallet: bugfix for broken oracle_wallet_password (oravirt#406)
- oraswdb_manage_patches: refresh opatch lsinv after opatch rollback (oravirt#405)
> Release 4.4.2 - 6th Beta Release of ansible-oracle

- changelogs/fragments/hugepages.yml
- roles/orahost/README.md
- roles/orahost/tasks/main.yml
The configuration of hugepages should be disabled by configure_hugepages=false. That was broken, because the nr_hugepages has been set to 0 instead ignore the configuration of sysctl for hugepages.
fixes #410
> orahost: fix for broken configure_hugepages=false

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/assert.yml
- changelogs/fragments/bash.yml
- changelogs/fragments/default_dbpass.yml
- changelogs/fragments/default_dbpass_dbca.yml
- changelogs/fragments/default_gipass.yml
- changelogs/fragments/default_gipass2.yml
- changelogs/fragments/dependabot_408.yml
- changelogs/fragments/docs.yml
- changelogs/fragments/hugepages.yml
- changelogs/fragments/os_oracle.yml
- changelogs/fragments/role_sparation.yml
- galaxy.yml
v4.5.0
======
Minor Changes
-------------
- Change Shebang to /usr/bin/env bash (oravirt#409)
- Documentation updates (oravirt#389)
- build(deps): bump ansible-core from 2.15.8 to 2.15.9 in /tools/dev (oravirt#408)
- minor fixes for role separation in Oracle Restart (oravirt#409)
- oradb_manage_db: Assert SYS password in inventory before dbca (oravirt#409)
Breaking Changes / Porting Guide
--------------------------------
- Removed oracle_password - use default_gipass as replacement (oravirt#409)
- orahost: Removed fixed password for oracle and grid from defaults (oravirt#409)
- orasw_meta: Removed default passwords from default_dbpass and dbpasswords (oravirt#409)
- oraswgi_install: Removed default password from default_gipass (oravirt#409)
Security Fixes
--------------
- orahost: Removed …
> Release 4.5.0 - 7th Beta Release of ansible-oracle

- changelogs/fragments/oracle_db_mem_totalmb.yml
- example/beginner/ansible/inventory/group_vars/dbfs/database_DB1.yml
- example/beginner_patching/ansible/inventory/host_vars/beginner-dbfs-patching-151-192-168-56-162.nip.io/databases.yml
- extensions/molecule/dbfs/side_effect.yml
- extensions/molecule/shared_config/inventory/group_vars/all/oracle_db.yml
- roles/orasw_meta/README.md
- roles/orasw_meta/defaults/main.yml
- roles/orasw_meta/tasks/assert_oracle_databases.yml
The attribute oracle_db_mem_totalmb should not be used in oracle_databases anymore. Use sga_target and pga_aggregate_target in oracle_databases.init_parameters as replacement.
The assert checks, if oracle_db_mem_totalmb is defined without sga_target or oracle_db_mem_totalmb is not used with an entry for sga_target in oracle_databases.init_parameters.
The assert of oracle_database is enabled by default. This could be disabled by setting:
orasw_meta_assert_oracle_databases: false
> orasw_meta: added assert for oracle_db_mem_totalmb in oracle_databases

- changelogs/fragments/orasw_download.yml
- roles/orasw_download_patches/tasks/main.yml
This extension is needed for the upcoming RAC-Support.
> orasw_download_patches: Download OPatch for GI/Restart

- changelogs/fragments/assert_pdbs.yml
- changelogs/fragments/molecule.yml
- changelogs/fragments/oradb_facts.yml
- changelogs/fragments/oradb_facts2.yml
- changelogs/fragments/oradb_facts3.yml
- extensions/molecule/dbfs/side_effect.yml
- extensions/molecule/shared_config/inventory/group_vars/all/oracle_db.yml
- roles/oradb_facts/tasks/db_facts.yml
- roles/oradb_manage_db/tasks/manage-db.yml
- roles/oradb_manage_grants/tasks/main.yml
- roles/oradb_manage_parameters/tasks/main.yml
- roles/oradb_manage_pdb/tasks/main.yml
- roles/oradb_manage_profiles/tasks/main.yml
- roles/oradb_manage_redo/tasks/main.yml
- roles/oradb_manage_roles/tasks/main.yml
- roles/oradb_manage_services/tasks/main.yml
- roles/oradb_manage_statspack/tasks/main.yml
- roles/oradb_manage_tablespace/tasks/main.yml
- roles/oradb_manage_users/tasks/main.yml
- roles/orasw_meta/tasks/assert_oracle_databases.yml
- roles/orasw_meta_internal/README.md
- roles/orasw_meta_internal/defaults/main.yml
The role oradb_facts ignores failures during fact gathering for the database, when `oradb_facts_ignore_unreachable: true` is used in item of `oracle_databases`.
The fact result is used in all other `oradb_manage_`-roles to ignore a unreachable database.
This allow an execution of roles from ansible-oracle when the database is not reachable for changes without aborting the play.
> oradb_facts_ignore_unreachable in oracle_databases

- changelogs/fragments/420_yaml_indents.yml
- roles/oradb_rman/tasks/main.yml
- roles/orasw_meta/tasks/assert_oracle_sw_patches.yml
- roles/oraswgi_manage_patches/tasks/post_install_patch.yml
It showed particulary in oradb_rman role, where due to additional indents in `>-` block unwanted newlines were produced by builtin.shell command line, which caused the task to fail. Due to the syntax of commandline produced this however did not produce exitcode != 0 and was not recognised as failed by ansible.
Here is how a command looked like:
cmd: "/u01/app/oracle/bin/rman_backup.sh\\**n**  -a parameter\\**n**  -s CDB1\\**n**  -r /u01/app/oracle/rman\n  -l /u01/app/oracle/rman/log | tee -a /var/log/oracle/rman/log/rman_parameter.log"
This of course produced following output:
stdout: "Missing parameter for ORACLE_SID\n \nUsage:\n  rman_backup.sh -a <action> -s <ORACLE_SID|DB_NAME> [-r <Directory>]\n            [-l <Directory>] [-c <CATALOGCONNECT>] [-t <TARGETCONNECT>]\n …
> bug: extra indents in yaml blocks produce unwanted newlines

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/420_yaml_indents.yml
- changelogs/fragments/cluvfy_oraswgi_install.yml
- changelogs/fragments/cluvy.yml
- changelogs/fragments/oracluvfy.yml
- changelogs/fragments/orahost_dir.yml
- changelogs/fragments/orahost_meta_limits.yml
- changelogs/fragments/oraswdb_install.yml
- changelogs/fragments/run_once.yml
- galaxy.yml
v4.7.0
======
Minor Changes
-------------
- Replace run_once: _oraswgi_meta_configure_cluster with when condition (oravirt#422)
- molecule: download for current cluvfy added (oravirt#423)
- oracluvfy: New role for managing cluvfy (oravirt#423)
- orahost_meta: increase defaults for memlock limits from 0.90 to 0.91 for cluvfy (oravirt#423)
- oraswgi_install: use role oracluvfy for cluvfy during installation (oravirt#423)
Bugfixes
--------
- oradb_rman: Removed unwanted newlines from rman_backup.sh command line (oravirt#420)
- orahost: fix wrong permissions in filesystem | Create directories (oravirt#424)
- oraswdb_install: fix broken Transfer oracle installfiles to server (oravirt#421)
- reviewed entire roles/ code basis and removed unwanted indents from yaml multiline blocks (oravirt#420) …
> Release 4.7.0 - 9th Beta Release of ansible-oracle

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/pdbadmin.yml
- galaxy.yml
v4.8.0
======
Minor Changes
-------------
- oradb_manage_pdb: added missing defaults for pdbadmin_user and pdbadmin_password (oravirt#426)
> Release 4.8.0 - 10th Beta Release of ansible-oracle

- changelogs/fragments/home_state.yml
- roles/oraswdb_install/tasks/install-home-db.yml
- roles/oraswgi_install/tasks/main.yml
grep has to ignore lines matching REMOVED="T"
> Fix for Issue #436 Consider home was removed earlier, leaving REMOVED=T

- changelogs/fragments/gipass.yml
- roles/oraswgi_install/tasks/assert.yml
default_gipass is a default for sysasmpassword or asmmonitorpassword. If both, sysasmpassword and asmmonitorpassword are set, it's not required to set default_gipass too. Thus missing default_gipass shouldn't fail assertion in that case.
> Fix for Issue #428: default_gipass is not required if sysasmpassword and asmmonitorpassword are set

- changelogs/fragments/sysctl.yml
- roles/orahost/README.md
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
This PR adds 2 parameters which allow to change the sysctl file in which oracle will write its main and hugepages settings:
* `oracle_sysctl_file`
* `oracle_hugepages_sysctl_file`
It also allows to specify an override directly in `oracle_sysctl`/`oracle_hugepages` by specifying one of those attributes:
* `state` - defaults to `present`, but can also accept `absent` in order to move settings from default to custom sysctl file
* `sysctl_file` - allows to change the location on per-element basis
Those additional attributes are not directly documentet as those 2 lists are considered internal and should not normally be tampered with. They are however needed should one want to move those settings from default `/etc/sysctl.conf` to for example a file under `/etc/sysctl.d/...`. Especially the …
> add oracle_sysctl_file and oracle_hugepages_sysctl_file variables

- changelogs/fragments/etc_hosts.yml
- roles/orahost/README.md
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
Adds  manually configured host entires to /etc/hosts, optionally along with host aliases
> Add a list of additional hosts to /etc/hosts

- changelogs/fragments/orahost_meta_env.yml
- roles/orahost_meta/README.md
- roles/orahost_meta/defaults/main.yml
- roles/oraswdb_install/vars/main.yml
- roles/oraswgi_install/tasks/19.3.0.0.yml
- roles/oraswgi_install/tasks/runcluvfy.yml
- roles/oraswgi_install/vars/main.yml
* Setting CV_ASSUME_DISTID enables forward compatibility for cluvfy, gridSetup etc to run on Linux 8 and 9, also with 19.3 base release. This might obsolete the need for Gold Images here.
* On hardened systems, the system's default tempdir (e.g. /tmp) usually is noexec flagged, which denies execution of java or shell code. To make GI setup more hardening-proof, temporary directory will be changed to /u01/stage/tmp.
> Enhancement#452 oracle script env

- changelogs/fragments/molecule_image.yml
- changelogs/fragments/orahost_meta_env.yml
- extensions/molecule/dbfs/converge.yml
- extensions/molecule/dbfs/molecule.yml
- extensions/molecule/default/molecule.yml
- roles/oracluvfy/tasks/execute_cluvfy.yml
- roles/orahost_meta/README.md
- roles/orahost_meta/defaults/main.yml
- roles/oraswdb_install/tasks/19.3.0.0.yml
- roles/oraswdb_install/vars/main.yml
- roles/oraswgi_install/tasks/19.3.0.0.yml
This is a fix for #453 .
`_JAVA_OPTIONS` is only set when `oracle_tmp_stage` != /tmp due to issues with `GridSetup.sh -applyRU` for 21c.
The default for `oracle_tmp_stage` is /tmp when `ansible-fips` is disabled or `{{ oracle_stage }}/tmp` when enabled.
The owner, group and priviledges for `oracle_tmp_stage` are set to same values as `/tmp` on normal linux servers.
The `CV_ASSUME_DISTID` is set to `OL{{ ansible_distribution_major_version }}` for RHEL/OL when not RHEL9/OL9 and set to `OL8` when RHEL9/OL9.
`SLES15` is default for SuSE at the moment. This could be changed in next PRs.
`cluvfy` is always executed without `CV_ASSUME_DISTID`, because the tool is compatible for all supported plattforms when most current version is used.
> This is a fix for #453 .

- changelogs/fragments/hugepages.yml
- roles/orahost/README.md
- roles/orahost/defaults/main.yml
- roles/orahost/tasks/main.yml
This PR will make `orahost` role to set `vm.hugetlb_shm_group` to the current GID or `oracle_user` when setting up huge_pages.
This is [recommended by Oracle](https://support.oracle.com/epmos/faces/DocContentDisplay?id=3010862.1) and in some new Distributions (like SLES 15.4 or RHEL9) even mandatory.
See Doc ID 2491966.1, 3010862.1, 1519770.1 and similar for more Details from Oracle on this topic.
> Add task/entry to set vm.hugetlb_shm_group

- changelogs/fragments/orahost_meta_kernel.yml
- roles/orahost/README.md
- roles/orahost/defaults/main.yml
- roles/orahost_meta/README.md
- roles/orahost_meta/defaults/main.yml
- roles/orahost_meta/tasks/aggregate_processes.yml
- roles/orahost_meta/tasks/aggregate_sgas.yml
- roles/orahost_meta/tasks/calculate_kernel_semaphores.yml
- roles/orahost_meta/tasks/main.yml
Changes:
* `max_size_in_gb_hugepages`: When `configure_hugepages_by: memory`, limit GB of hugepages to a percentage of physical memory to prevent overallocating
* `nr_hugepages_percent`: Replace fixed hugepage size (2MB) by system's actual hugepage size (just in case it changes) and add two pages *per instance*, which is empirically better than just two pages overall
* `nr_hugepages_memory': Same as `nr_hugepages_percent`, plus hugepages cap `max_size_in_gb_hugepages`
Enhancements:
* Provides a few aggregates man can use to calculate kernel parameters, i.e.
* `oracle_databases_processes_sum`: Sum of processes init-Parameter over all databases
* `oracle_databases_processes_max`: Largest processes init-Parameter over all databases
* `oracle_databases_sga_sum`: Sum of max(sga_target, …
> Enable calculation of several kernel parameters

- changelogs/fragments/opatch_tmpdir.yml
- plugins/modules/oracle_opatch.py
- roles/oraswgi_manage_patches/tasks/loop_patchid.yml
* Supports configurable temp directories other than /tmp, which usually is noexec flagged on hardened systems
* passes orahost_meta_tmpdir and orahost_meta_java_options introduced with #452 into oracle_opatch.py
> oracle_opatch.py needs to support configurable temp directory

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/apply_patches_gi.yml
- changelogs/fragments/cluvfy.yml
- changelogs/fragments/etc_hosts.yml
- changelogs/fragments/gipass.yml
- changelogs/fragments/global_handler_lint.yml
- changelogs/fragments/global_handlers.yml
- changelogs/fragments/home_state.yml
- changelogs/fragments/hugepages.yml
- changelogs/fragments/hugepages_grub.yml
- changelogs/fragments/lint-hosts.yml
- changelogs/fragments/logrotate.yml
- changelogs/fragments/molecule_image.yml
- changelogs/fragments/ocenv.yml
- changelogs/fragments/opatch_tmpdir.yml
- changelogs/fragments/orahost_meta_env.yml
- changelogs/fragments/orahost_meta_kernel.yml
- changelogs/fragments/oraswdb_manage_patches.yml
- changelogs/fragments/oraswgi_install_refactor.yml
- changelogs/fragments/oraswgi_manage_patches.yml
- changelogs/fragments/role_separation.yml
- changelogs/fragments/sysctl.yml
- changelogs/fragments/systemd.yml
- galaxy.yml
v4.9.0
======
This is the 1st production release of ansible-oracle 4.x. The RAC support was the last missing option in 4.x compared to 3.12.0. A documentation for migration from 3.12.0 to 4.x is work in progress.
Minor Changes
-------------
- added option to disable transparent hugepages in grub (oravirt#460)
- bugfix set custom environment for executables with oracle_script_env (oravirt#458)
- global_handlers: Introduce a global handlers role (oravirt#455)
- global_handlers: Reboot handler improvements, restart_on_requirement=false, ansible-lint (oravirt#457)
- molecule: added MOLECULE_IMAGE for custom images and support for SuSE (oravirt#458)
- oracle_opatch.py needs to support configurable temp directory  (oravirt#462)
- orahost: Add a list of additional …
> Release 4.9.0 - 1st production Release of ansible-oracle

- README.adoc
- README.md
- changelogs/fragments/rhel_ol7.yaml
- doc/featurelist.adoc
- example/beginner/vagrant/Vagrantfile
- example/rac/vagrant/Vagrantfile
- extensions/molecule/default/molecule.yml
- roles/common/README.md
- roles/common/defaults/main.yml
The support for OL/RHEL7 will be stopped, because EPEL archived all RPMs on their official repositories. No more bugfixes or security updates for RPMs anymore.
`ansible-oracle` depends on some RPMs from that repository.
The maintenance support for RHEL7 has been ended on 30 June 2024.
The Premiere Support for OL7 will end 31 Decembre 2024.
The code  from `ansible-oracle` may work with OL/RHEL7 but all tests won't be done against this OS anymore.
> End of Life for Oracle Linux 7 and RHEL7

- .github/workflows/changelog-lint.yml
- .pre-commit-config.yaml
- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/ansible-lint.yml
- changelogs/fragments/ansible-lint2.yml
- changelogs/fragments/antsibull.yml
- changelogs/fragments/beginner_patching.yml
- changelogs/fragments/builder.yml
- changelogs/fragments/collection_dependencies.yml
- changelogs/fragments/molecule_dbfs.yml
- changelogs/fragments/molecule_dbfs_ol9.yml
- changelogs/fragments/ocenv.yml
- changelogs/fragments/orahost_meta_gi.yml
- changelogs/fragments/oraswdb_manage_patches.yml
- changelogs/fragments/prepatching_19c.yml
- changelogs/fragments/rhel_ol7.yaml
- example/beginner_patching/ansible/requirements.yml
- example/rac/ansible/requirements.yml
- galaxy.yml
- tools/dev/requirements_antsibull.txt
v4.10.0
=======
`ansible-oracle` 4.10.0 supports OL9/RHEL9 without the need to install the software
from a golden image. The exmples for beginner_patching and RAC have been fixed to
use the new pre-patching support in `oraswdb_install`.
Minor Changes
-------------
- added missing collection dependencies (oravirt#469)
- ansible-builder: moved to new base image (oravirt#470)
- ansible-lint: Update ansible-lint to 24.7.0 (oravirt#471)
- ansible-lint: fqcn[action-core] for ansible.builtin.yum due to OL7 compatibility (oravirt#471)
- antsibull-changelog: Upgrade version 0.29.0 (oravirt#472)
- beginner_patching: updated example to ansible-oracle 4.x (oravirt#469)
- molecule: changes to dbfs for new dbfs-ol9 szenario (oravirt#469)
- molecule: dbfs-ol9 for RDBMS …
> Release 4.10.0

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/apex.yml
- changelogs/fragments/apex_download.yml
- changelogs/fragments/beginner.yml
- changelogs/fragments/doc1.yml
- changelogs/fragments/molecule.yml
- changelogs/fragments/oraswgi_install.yml
- changelogs/fragments/ords.yml
- changelogs/fragments/sqlnet.yml
- changelogs/fragments/sqlnet_meta.yml
- changelogs/fragments/sqlnet_molecule.yml
- changelogs/fragments/sqlnet_rac.yml
- example/beginner_patching/ansible/requirements.yml
- example/rac/ansible/requirements.yml
- galaxy.yml
Roles for APEX and ORDS have been added in experimental state. The old issue with missing support for listener configuration in Oracle GI/Restart has been fixed. A new Playbook manage_sqlnet.ora has been added for easier configuration of listener.ora, sqlnet.ora and tnsnames.ora.
Minor Changes
-------------
- ORDS: new experimental role to install and configure ORDS on OracleLinux (oravirt#473)
- ansible-oracle Documentation fixes (oravirt#473)
- beginner_patching: Inventory for ORDS + APEX (oravirt#473)
- example rac: create multiple listener as example (oravirt#475)
- galaxy: added new collection as dependency for RAC/Restart listener configuration (oravirt#475)
- molecule: Added APEX and ORDS to dbfs-ol9 (oravirt#473)
- molecule: added 2nd listener for …
> Release 4.11.0

- changelogs/fragments/download.yml
- changelogs/fragments/orasw_meta.yml
- roles/orahost_meta/tasks/main.yml
- roles/orasw_download_patches/tasks/main.yml
> orasw_meta: empty oracle_databases broke orasw_download_patches

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/devsec.yml
- changelogs/fragments/download.yml
- changelogs/fragments/orasw_meta.yml
- example/beginner_patching/ansible/requirements.yml
- example/rac/ansible/requirements.yml
- galaxy.yml
v4.11.1
=======
Bugfixes
--------
- devsec: changed hosts=all to hosts={{ hostgroup | default('all') }} (oravirt#479)
- orasw_download_patches: bugfix for empty oracle_databases or oracle_pdbs (oravirt#480)
- orasw_meta: empty oracle_databases broke orasw_download_patches (oravirt#480)
> Release 4.11.1

- changelogs/fragments/tz_cdb_upgrade_issue.yml
- roles/oradb_tzupgrade/tasks/cdb.yml
When upgrading timezone for a CDB database it fails with:
```
TASK [opitzconsulting.ansible_oracle.oradb_tzupgrade : oradb_tzupgrade | Show facts for pdbs_info] ***                                                                                             
Wednesday 23 October 2024  22:15:43 +0200 (0:00:00.055)       0:03:57.589 *****                                                                                                                    
fatal: [mol-oracle-pdvmoras99-snapcdb]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '_oradb_tzupgrade_candidate_pdbs' is undefined. '_oradb_tzupgrade
_candidate_pdbs' is undefined\n\nThe error appears to be in '/home/devopsadm/.ansible/collections/ansible_collections/opitzconsulting/ansible_oracle/ …
```
> fix for _oradb_tzupgrade_candidate_pdbs fact

- changelogs/fragments/orahost_firewall.yml
- roles/orahost/defaults/main.yml
When using the orahost role on OL Linux 8, the the firewall_service variable is not populated with firewalld causing the disable_firewall taks to fail (do nothing)
> orahost firewall_service should default to firewalld on OL/EL 8

- changelogs/fragments/re_global_flags_fix.yml
- roles/orahost_meta/tasks/main.yml
Hello,
When trying to provision a new Oracle setup, the following error is raised:
```
TASK [opitzconsulting.ansible_oracle.orahost_meta : Extract SGA parameters, choose sga_max_size over sga_target if both are definied] ***
task path: /Users/talek/.ansible/collections/ansible_collections/opitzconsulting/ansible_oracle/roles/orahost_meta/tasks/main.yml:41 
Thursday 07 November 2024  18:43:16 +0200 (0:00:00.029)       0:00:12.053 *****                                                                                                                                                                                         
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: re.error: global flags not at the start of the expression at position 1
fatal: …
```
> fix for re global flags expression

- .ansible-lint
- .gitignore
- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/aggregate_sgas_fix.yml
- changelogs/fragments/ansible-lint.yml
- changelogs/fragments/motd.yml
- changelogs/fragments/orahost_firewall.yml
- changelogs/fragments/re_global_flags_fix.yml
- changelogs/fragments/remove_screen_from_default.yml
- changelogs/fragments/sga_calculation.yml
- changelogs/fragments/tz_cdb_upgrade_issue.yml
- changelogs/fragments/unarchive-check.yml
- example/beginner_patching/ansible/requirements.yml
- example/rac/ansible/requirements.yml
- galaxy.yml
v4.12.0
=======
Minor Changes
-------------
- ansible-lint: more excludes (oravirt#505)
- common: remove screen from default rhel8,9 package list (oravirt#496)
- orahost: firewall_service should default to firewalld on OL/EL 8 (oravirt#499)
Bugfixes
--------
- common: Exclude alias interfaces when templating motd.j2 (oravirt#486)
- common: force bool type in certain conditionals
- fix for re global flags when extracting sga/processes parameters in orahost_meta (oravirt#493)
- orahost_meta: Aggregate SGAs fails if no sga_target or sga_max_size is defined (oravirt#498)
- orahost_meta: Applying 'lower' filter to oracle_databases+oracle_asm_instance converts list to string (oravirt#484)
- oraswdb_manage_patches, oraswgi_manage_patches: make unarchive check work for combo patches too …
> Release 4.12.0

- plugins/modules/oracle_grants.py
I have found a problem with the `oracle_grants` module that is used to revoke or grant permissions. The function is missing a parameter.
I have a use case where via a playbook the application owner needs specific grant to finish in maintenance window his tasks for and after the job is done on his end the same playbook is used to revoke the provided grants.
I caught an exception that run in trace condition, see provided log output below and current running ansible version.
The problem also exists in the old v3.12 `(tag v3.12.0)` which is no longer maintained.
```
TASK [opitzconsulting.ansible_oracle.oradb_manage_grants : Manage schema grants (cdb)] ************************************************************************************************************************************************ …
```
> [BUG] missing parameter in remove_grants function im module 

- changelogs/fragments/create_omf_database.yml
- plugins/modules/oracle_db.py
- roles/oradb_manage_db/tasks/manage-db.yml
Starting with Oracle 18.4, dbca has added the -useOMF parameter for creating OMF enabled databases. This pull request implements this feature.
> Add feature to create OMF enabled databases

- changelogs/fragments/scripts-folder-configurable.yml
- roles/common/README.md
- roles/common/defaults/main.yml
- roles/oradb_manage_db/tasks/main.yml
- roles/oraswdb_install/templates/dotprofile-home.j2
- roles/oraswdb_install/vars/main.yml
As previously discussed with @Rendanic , there is a hard coded ".Scripts" folder created where e. g. "change_pdb.sql" is placed.
The folder name should be made configurable, so that it can be adapted to other naming conventions.
Additionally (but feel free to cherry pick), the script "change_pdb.sql" should only be copied to the target when `oracle_pdbs` is defined. So there's no unnecessary clutter when CDB/PDB architecture isn't used.
Cheers,
Uwe
> Scripts folder should be configurable

- changelogs/fragments/oradb_tzupgrade_role_dependency.yml
- roles/oradb_tzupgrade/README.md
- roles/oradb_tzupgrade/meta/main.yml
`_ora_home_db` is defined in `orasw_meta_internal` role and it should be added in the dependencies list. Otherwise, we may end up with an error like:
```
TASK [opitzconsulting.ansible_oracle.oradb_tzupgrade : oradb_tzupgrade | Perform timezone checks for CDB$ROOT and PDB$SEED first] *********************************************************************************************************************************************************
fatal: [vmorastest01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '_oracle_home_db' is undefined. '_oracle_home_db' is undefined\n\nThe error appears to be in '/home/devopsadm/profidans/lib/ansible_collections/opitzconsulting/ansible
_oracle/roles/oradb_tzupgrade/tasks/cdb.yml': line 2, column 3, but may\nbe …
```
> oradb_tzupgrade: Add orasw_meta_internal as a dependent role

- changelogs/fragments/create_omf_database.yml
- changelogs/fragments/pdbs-default-for-patching.yml
- roles/oradb_manage_pdb/tasks/main.yml
There is an issue when you run Playbooks that call the role "oradb_manage_pdb", when these are run on non-CDB databases.
- The task `manage pdb(s)` enters the `with_nested:` loop, despite the condition `when: oracle_pdbs is defined`.
- The reason is that the `when` part is evaluated _after_ parsing the loop variables. This results in the error:
`msg: '''oracle_pdbs'' is undefined. ''oracle_pdbs'' is undefined'`
- This is expected behaviour of Ansible. See [Using Conditionals in Loops](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#using-conditionals-in-loops) in the Ansible docs.
- Workarounds:
- Use `--skip-tags "pdb"` when running affected playbooks (e.g. "opatch.yml").
- Remove or comment out the calls to "oradb_manage_pdb". But this isn't viable …
> manage_pdb: Enter nested loop only when oracle_pdbs has an entry

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/ansible-lint.yml
- changelogs/fragments/apex_sw_local.yml
- changelogs/fragments/create_omf_database.yml
- changelogs/fragments/doc-local-install.yml
- changelogs/fragments/oradb_tzupgrade_role_dependency.yml
- changelogs/fragments/pdbs-default-for-patching.yml
- changelogs/fragments/scripts-folder-configurable.yml
- changelogs/fragments/scripts_folder_fix.yml
- changelogs/fragments/typo-zauberkasten.yml
- example/beginner_patching/ansible/requirements.yml
- example/rac/ansible/requirements.yml
- galaxy.yml
- roles/common/README.md
- roles/orahost_meta/README.md
v4.13.0
=======
Minor Changes
-------------
- Added a guide on how to install Ansible-Oracle manually on a server without Internet access. (oravirt#506)
- Fix typo for sql_zauberkasten (oravirt#509)
- ansible-lint: more excludes (oravirt#505)
- create OMF enabled databases using dbca's -useOMF flag (oravirt#507)
- manage_pdb: Enter nested loop only when oracle_pdbs has an entry (oravirt#507)
- oraapex: Added missing option to copy source from remote or local host (oravirt#512)
- oradb_manage_db: make hard coded folder .Scripts configurable (oravirt#511)
- oradb_tzupgrade: Add orasw_meta_internal as a dependent role (oravirt#510)
Bugfixes
--------
- orahost_meta: move scripts_folder variable from common to orahost_meta (oravirt#504)
> Release 4.13.0

- changelogs/fragments/oradb_tzupgrade_pdbs.yml
- roles/oradb_tzupgrade/tasks/cdb.yml
- roles/oradb_tzupgrade/tasks/main.yml
- roles/oradb_tzupgrade/tasks/non_cdb.yml
When many PDBs with long names are present, Oracle listagg aggregate function fails. This PR fixes this issue by doing the concatenation in Ansible using the map filter.
> oradb_tzupgrade: compose the comma delimited list of PDBs using map
